### ISSUE TITLE
Set fzf default opts only when not set.

### ISSUE THREAD

**Issue by GordianDziwis** [wookayin/fzf-fasd#2]
This keeps consistency, with the users fzf setup.

**Comment by wookayin** [comment]
I changed the behavior such that `FZF_DEFAULT_OPS` is not overwritten and the preferred flags (bind, reverse, etc.) are explicitly passed as command-line arguments. Please see commit e68e3e1. Would it work for you?

**Comment by GordianDziwis** [comment]
Works perfectly, thanks!
