### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [wookayin/fzf-fasd#3]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license.

Please add a license - if you don't have one in mind,  I recommend [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

**Comment by wookayin** [comment]
Added the LICENSE file. Thanks!

**Comment by unixorn** [comment]
Adding in https://github.com/unixorn/awesome-zsh-plugins/pull/783, thanks!
