### ISSUE TITLE
Configurable --height

### ISSUE THREAD

**Issue by noctuid** [wookayin/fzf-fasd#4]
Awesome plugin! It would be nice if fzf-fasd left `--height` alone or at least had a variable for configuring options. I want to have a bigger height than 50%. Fzf's completions use `FZF_TMUX_HEIGHT` (or `FZF_DEFAULT_OPTIONS`) as a default, for example. Enhancd's completions use `FZF_TMUX_HEIGHT` if set also.

**Comment by wookayin** [comment]
Thanks for the suggestion. Now fzf-fasd respects `FZF_TMUX_HEIGHT`, `FZF_DEFAULT_OPTS` and `FZF_FASD_OPTS` (in the order). Please see commit 5552cdc and the README.
