### ISSUE TITLE
No need for separate plugin, This small function enough

### ISSUE THREAD

**Issue by thamaraiselvam** [wookayin/fzf-fasd#6]
This one function enough to make it work

```
t() {
  fasdlist=$( fasd -d -l -r $1 | \
    fzf --query="$1 " --select-1 --exit-0 --height=25% --reverse --tac --no-sort --cycle) &&
    cd "$fasdlist"
}
```

Source: https://www.gregorykapfhammer.com/software/tool/productivity/2017/05/08/Directory-Zooming/

**Comment by wookayin** [comment]
Yeah that works and thanks for the pointer.

But I wanted to make `z`, `f`, etc., also work. In addition, tab completion support is another feature this plugin is adding, which I don't think is trivially possible by having such a small function.
