### ISSUE TITLE
fasd interactive > fzf

### ISSUE THREAD

**Issue by drewauff** [wookayin/fzf-fasd#7]
Is there anyway to pipe/push `fasd -i` into fzf while also removing the scores column?

**Comment by wookayin** [comment]
Sorry, I don't understand your question. Can you provide more information?

**Comment by drewauff** [comment]
hmm, I want to use fasd's interactive mode in fzf, how?

**Comment by wookayin** [comment]
If you are using fzf as an interactive UI for fasd, what's the point of using `fasd -i` (the interactive mode of fasd)?

**Comment by drewauff** [comment]
fair enough, but how can I remove/hide the scores from the interactive mode? they are not really needed, I mean we dont really need to the "scores" all the time.

I have tried using cut and awk to remove the scores column either way messes it up.

Would be awesome if you added a switch/flag to accompany -i to hide the scores column.

**Comment by wookayin** [comment]
Your feature request seems to be related to fasd and has nothing to do with this plugin. However, note that fasd is no longer maintained.

`fasd -i` prints the candidates into stderr, so you'll need [pipe stderr output](https://stackoverflow.com/questions/2342826/how-can-i-pipe-stderr-and-not-stdout):

```
fasd -i 2> >(awk '{print $1 "\t" $3}')
```
